// Google Reviews Data - Real reviews from Vitano Business Profile
// Source: https://share.google/U585qcYeD0CJ8V6UW
// These are authentic customer reviews sourced directly from Google Business Profile

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Yogesh Verma',
    role: 'Verified Customer',
    quote: 'Had amazing experience while using these products. Would recommend everyone to try once for better life.',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjW2JHj0MjzEpSeNSeJQ-F24xeM1G_bDgNTZKJTzVTO_bcHCzf-b=s64-c-rp-mo-br100',
    date: '5 months ago',
  },
  {
    id: 2,
    name: 'pankaj jamdagni',
    role: 'Verified Customer',
    quote: 'It is Good Experience to buy from here..i had bought Hing and Walnut Best quality from here.',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjWfOvxKQMpwLHi8XD93l1-K7NNsnLg-dvM5dpDIAMttEkLLOg=s64-c-rp-mo-br100',
    date: '5 months ago',
  },
  {
    id: 3,
    name: 'Nikhil Yadav',
    role: 'Verified Customer',
    quote: 'Fresh and good-quality dry fruits. Prices are reasonable and packing is nice. Highly recommended.',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjWrcbo6ZDOu88E-qDKhjPBImwNZeMB00oMfmUwfuFgWzDEy6WJB=s64-c-rp-mo-br100',
    date: '5 months ago',
  },
  {
    id: 4,
    name: 'sachin saini',
    role: 'Verified Customer',
    quote: 'Best quality product at reasonable price. Superb product',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjWuJ1d4n2e_DlSLagZszP3UsRPjmVoOcTTxJN01EKNxzx0Z4y2qgA=s64-c-rp-mo-br100',
    date: '5 months ago',
  },
  {
    id: 5,
    name: 'Chetan Chauhaan',
    role: 'Verified Customer',
    quote: 'Fresh and pure product',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a/ACg8ocKG1eDXrmYjFud1g9qPF-JIGCXohb97CYE4x9Fa12HiAn8rXg=s64-c-rp-mo-br100',
    date: '5 months ago',
  },
  {
    id: 6,
    name: 'Nawal Verma',
    role: 'Verified Customer',
    quote: 'Just Used this brand. Generally I am not the guy who try new product but this time I find this and this is As Good as big brand',
    rating: 4,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjU3D2prYgn6mqfg_VszjlDOYgGM3Ugo7LARHSsPLQu95TlsGdiv=s64-c-rp-mo-ba12-br100',
    date: '2 weeks ago',
  },
  {
    id: 7,
    name: 'Ankit Agnihotri',
    role: 'Verified Customer',
    quote: 'Really Rich taste and Quality. Strongly Recommended to Everyone atleast taste once.',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjVzkn5xUSFng02b8f137m0iEK-rTgVt2TS0T4xc2Ui7TAdKE2w=s64-c-rp-mo-br100',
    date: '2 weeks ago',
  },
  {
    id: 8,
    name: 'Lakshay',
    role: 'Verified Customer',
    quote: 'Fresh and good product very Nice quality',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a-/ALV-UjVTGo3v_BXxGMwlnFLtBdHMkZRnRM0-Vaq4sTNu-3qtEcJXZK8=s64-c-rp-mo-br100',
    date: '3 weeks ago',
  },
  {
    id: 9,
    name: 'Manisha Valmiki',
    role: 'Verified Customer',
    quote: 'Good and fresh and tasty Hing vitano',
    rating: 5,
    image: 'https://lh3.googleusercontent.com/a/ACg8ocL6NABzpKrolsOLn7n05wPbI2uh6jCw749SjIOn2538_aSm8A=s64-c-rp-mo-br100',
    date: 'a month ago',
  },
];
